### ISSUE TITLE
Rplus doesn't activate?

### ISSUE THREAD

**Issue by FilSalustri** [gerardnico/dokuwiki-renderer-rplus#1]
Perhaps I'm missing something. I installed rplus; DK says it's enabled. But I see no changes in rendering. And I see no options in Configuration panel for rplus.
I'm using 2015-08-10a Detritus.

**Comment by gerardnico** [comment]
I just add more information in the installation section:
https://www.dokuwiki.org/plugin:rplus#installation

You need to  go to the "[Configuration Setting: renderer_xhtml](https://www.dokuwiki.org/config:renderer_xhtml)" and choose “Renderer Plus”.

**Comment by FilSalustri** [comment]
Thank you; that did the trick.
I notice one small problem that I'm not sure about.
See, for instance, http://deseng.ryerson.ca/dokuwiki/wiki:start.
There's two TOCs now.
I _assume_ that I just need to tweak my template to remove the default TOC?
(I'll give that a try; if that doesn't work, I'll probably post again.)

In any case, thanks very much for the fast response.

\V/_  /fas

_Prof. Filippo A. Salustri, Ph.D., P.Eng._
Email: salustri@ryerson.ca
Web: http://deseng.ryerson.ca/~fil/
ORCID: 0000-0002-3689-5112 http://orcid.org/0000-0002-3689-5112

**Comment by FilSalustri** [comment]
Nico,
With apologies, I'm stumped.
When I look at http://deseng.ryerson.ca/dokuwiki/wiki:start, for instance,
I see 2 TOCs with rplus enabled.

My template is based on the starter template from a couple versions ago -
Hrun I think?
Could you offer any advice on how I can make the usual TOC disappear?

(I've already looked through the code, and all I see that pertains is a
single line in script.js (of the template):
    var $toc = jQuery('#dw__toc h3');
I also find the function in inc/html.php, html_TOC() that builds the TOC,
which is then used in inc/template.php: tpl_TOC().
I'm afraid I'm just not good enough with PHP to understand what
renderer.php is doing to the point where I can adjust it.

Have you any advice?

\V/_  /fas

_Prof. Filippo A. Salustri, Ph.D., P.Eng._
Email: salustri@ryerson.ca
Web: http://deseng.ryerson.ca/~fil/
ORCID: 0000-0002-3689-5112 http://orcid.org/0000-0002-3689-5112

**Comment by gerardnico** [comment]
In your template, you need to call the function tpl_content with $prependTOC = false

``` php
<?php tpl_content($prependTOC = false) ?>
```

See http://xref.dokuwiki.org/reference/dokuwiki/nav.html?_functions/tpl_content.html

Good luck and have a nice sunday

**Comment by FilSalustri** [comment]
Nico,
It worked like a charm. Thanks!

Best,

\V/_  /fas

_Prof. Filippo A. Salustri, Ph.D., P.Eng._
Email: salustri@ryerson.ca
Web: http://deseng.ryerson.ca/~fil/
ORCID: 0000-0002-3689-5112 http://orcid.org/0000-0002-3689-5112
